[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.vnc"

[deploy]
startCommand = "python server/api_server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
